server:
  port: 8800
spring:
  application:
    name: kee-api-getway #指定服务名

# 指定 url 设置服务路由
#zuul:
#  routes:
#    item-service: #item-service这个名字是任意写的  http://localhost:8800/item-service/item/1  匹配路由规则会 走下面的url
#      path: /item-service/** #配置请求URL的请求规则
#      url: http://127.0.0.1:8888 #真正的微服务地址

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，将 6868 注册到 6969
    fetchRegistry: true #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://root:root@127.0.0.1:6868/eureka/ # 本地在启动一个
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中

#面向服务 配置zuul
zuul:
  routes:
    item-service:
      path: /item-service/** #配置请求URL的请求规则
      url: limeo-item #服务名




