server:
  port: 8888
spring:
  application:
    name: limeo-item #指定服务名
#注册中心
eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://root:root@127.0.0.1:6868/eureka/ # 服务注册需要 用户名密码
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中

management:
  security:
    enabled: false #是否开启actuator安全认证
