server:
  port: 8887

remote:
  item:
    url: http://127.0.0.1:8888/item/

spring:
  application:
    name: limoe-order

#注册中心
eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://root:root@127.0.0.1:6868/eureka/ #发现服务需要 用户名密码

#指定服务名  设置 负载均衡策略  随机策略 （ 默认为轮询 ）
limeo-item:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule