server:
  port: 6868 #服务端口

spring:
  application:
    name: limeo-eureka-6868

eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中，将 6868 注册到 6969
    fetchRegistry: false #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://root:root@127.0.0.1:6868/eureka/ # 本地在启动一个

security:
  basic:
    enabled: true #开启基于HTTP basic的认证
  user:
    name: root
    password: root
